ON_TRACK = "ON_TRACK"

OFF_TRACK = "OFF_TRACK"

BREAK_REMINDER = "BREAK_REMINDER"

FOCUS_STARTED = "FOCUS_STARTED"

FOCUS_COMPLETED = "FOCUS_COMPLETED"

NO_ACTIVE_SESSION = "NO_ACTIVE_SESSION"

NO_PLANNER_FOUND = "NO_PLANNER_FOUND"

NO_NOTIFICATION = "NO_NOTIFICATION"

WELCOME_BACK = "WELCOME_BACK"

PRODUCTIVITY_IMPROVING = "PRODUCTIVITY_IMPROVING"

KEEP_GOING = "KEEP_GOING"

GREAT_JOB = "GREAT_JOB"