import jsPDF from "jspdf";

export const exportReportPDF = (
  report: any,
  user: {
    full_name: string;
    role: string;
    email: string;
  }
) => {
  const pdf = new jsPDF();

  let y = 20;

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(22);
  pdf.setTextColor(79, 70, 229);

  pdf.text("FocusGuard AI", 20, y);

  y += 8;

  pdf.setFontSize(12);
  pdf.setTextColor(100);

  pdf.text(
    "Digital Attention Intelligence Platform",
    20,
    y
  );

  y += 12;

  pdf.setDrawColor(220);
  pdf.line(20, y, 190, y);

  y += 12;

  pdf.setFontSize(18);
  pdf.setTextColor(0);

  pdf.text(
    `${report.report_type.toUpperCase()} REPORT`,
    20,
    y
  );

  y += 12;

  pdf.setFontSize(11);

  pdf.text(
    `Generated: ${new Date().toLocaleDateString()}`,
    20,
    y
  );

  y += 10;

  pdf.text(
    `User: ${user.full_name}`,
    20,
    y
  );

  y += 8;

  pdf.text(
    `Role: ${user.role}`,
    20,
    y
  );

  y += 8;

  pdf.text(
    `Email: ${user.email}`,
    20,
    y
  );

  y += 14;

  pdf.setDrawColor(220);
  pdf.line(20, y, 190, y);

  y += 12;

  pdf.setFont("helvetica", "bold");

  pdf.text("Focus Score", 20, y);

  pdf.text(
    `${report.focus_score}%`,
    140,
    y
  );

  y += 10;

  pdf.text("Active Time", 20, y);

  pdf.text(
    report.active_time,
    140,
    y
  );

  y += 10;

  pdf.text("Idle Time", 20, y);

  pdf.text(
    report.idle_time,
    140,
    y
  );

  y += 10;

  pdf.text("Total Time", 20, y);

  pdf.text(
    report.total_time,
    140,
    y
  );

  y += 18;

  pdf.setFontSize(16);

  pdf.text(
    report.report_type === "weekly"
      ? "Daily Breakdown"
      : "Weekly Breakdown",
    20,
    y
  );

  y += 10;

  pdf.setFontSize(11);

  const rows =
    report.daily_breakdown ??
    report.weekly_breakdown;

  rows.forEach((item: any) => {
    if (y > 270) {
      pdf.addPage();
      y = 20;
    }

    pdf.setFont(
      "helvetica",
      "bold"
    );

    pdf.text(
      item.day ?? item.week,
      20,
      y
    );

    pdf.setFont(
      "helvetica",
      "normal"
    );

    y += 7;

    pdf.text(
      `Active : ${item.active_time}`,
      30,
      y
    );

    y += 7;

    pdf.text(
      `Idle : ${item.idle_time}`,
      30,
      y
    );

    y += 10;
  });

  pdf.setFontSize(10);

  pdf.setTextColor(120);

  pdf.text(
    "Generated by FocusGuard AI",
    20,
    287
  );

  pdf.save(
    `${report.report_type}-report.pdf`
  );
};